spring.application.name=firma-rehberi

#mysql veritabanı bağlantı ayarları
spring.datasource.url=jdbc:mysql://localhost:3306/staj_db?serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=change35
spring.datasource.drive-class-name=com.mysql.jdbc.Driver

#jba / hibernate ayarları 
#springin tablolara müdahale etmesini istemiyorsak none olarak ayarlıyoruz
spring.jpa.hibernate.ddl-auto=none

#hibernatetin oluşturduğu sql sorgularını konsola yazdır
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true